name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root directory
      run: ls -la

    - name: List files in demo directory
      run: ls -la demo

    - name: Make gradlew executable
      run: chmod +x demo/gradlew

    - name: Build with Gradle
      working-directory: demo
      run: ./gradlew clean build -x test

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > id_rsa
        chmod 600 id_rsa
        scp -i id_rsa demo/build/libs/demo-0.0.1-SNAPSHOT.jar ${USER}@${HOST}:/home/ubuntu/backend
        ssh -i id_rsa ${USER}@${HOST} << EOF
        sudo systemctl stop spring-boot-app.service || true
        sudo cp /home/ubuntu/backend/demo.jar /opt/spring-boot-app/backend
        sudo systemctl start spring-boot-app.service
        EOF
