name: Deploy Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Write the private key to a file
        echo "${SSH_KEY}" > id_rsa
        chmod 600 id_rsa

        # Copy the build artifact to the EC2 instance
        scp -i id_rsa build/libs/demo-0.0.1-SNAPSHOT ${USER}@${HOST}:/home/ubuntu/backend

        # SSH into the EC2 instance and deploy the application
        ssh -i id_rsa ${USER}@${HOST} << 'EOF'
        # Stop the running instance of the application
        sudo systemctl stop spring-boot-app.service || true

        # Replace the old JAR with the new one
        sudo cp /home/ubuntu/backend /opt/spring-boot-app/backend

        # Start the application again
        sudo systemctl start spring-boot-app.service
        EOF
